// Autogenerated from Pigeon (v4.2.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package fr.mohachouch.native_http_client;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/**Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class NativeHttpClient {

  public enum EventMessageType {
    RESPONSE_STARTED(0),
    READ_COMPLETED(1);

    private final int index;
    private EventMessageType(final int index) {
      this.index = index;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ResponseStarted {
    private @NonNull Map<String, List<String>> headers;
    public @NonNull Map<String, List<String>> getHeaders() { return headers; }
    public void setHeaders(@NonNull Map<String, List<String>> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"headers\" is null.");
      }
      this.headers = setterArg;
    }

    private @NonNull Long statusCode;
    public @NonNull Long getStatusCode() { return statusCode; }
    public void setStatusCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"statusCode\" is null.");
      }
      this.statusCode = setterArg;
    }

    private @NonNull String statusText;
    public @NonNull String getStatusText() { return statusText; }
    public void setStatusText(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"statusText\" is null.");
      }
      this.statusText = setterArg;
    }

    private @NonNull Boolean isRedirect;
    public @NonNull Boolean getIsRedirect() { return isRedirect; }
    public void setIsRedirect(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isRedirect\" is null.");
      }
      this.isRedirect = setterArg;
    }

    /**Constructor is private to enforce null safety; use Builder. */
    private ResponseStarted() {}
    public static final class Builder {
      private @Nullable Map<String, List<String>> headers;
      public @NonNull Builder setHeaders(@NonNull Map<String, List<String>> setterArg) {
        this.headers = setterArg;
        return this;
      }
      private @Nullable Long statusCode;
      public @NonNull Builder setStatusCode(@NonNull Long setterArg) {
        this.statusCode = setterArg;
        return this;
      }
      private @Nullable String statusText;
      public @NonNull Builder setStatusText(@NonNull String setterArg) {
        this.statusText = setterArg;
        return this;
      }
      private @Nullable Boolean isRedirect;
      public @NonNull Builder setIsRedirect(@NonNull Boolean setterArg) {
        this.isRedirect = setterArg;
        return this;
      }
      public @NonNull ResponseStarted build() {
        ResponseStarted pigeonReturn = new ResponseStarted();
        pigeonReturn.setHeaders(headers);
        pigeonReturn.setStatusCode(statusCode);
        pigeonReturn.setStatusText(statusText);
        pigeonReturn.setIsRedirect(isRedirect);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("headers", headers);
      toMapResult.put("statusCode", statusCode);
      toMapResult.put("statusText", statusText);
      toMapResult.put("isRedirect", isRedirect);
      return toMapResult;
    }
    static @NonNull ResponseStarted fromMap(@NonNull Map<String, Object> map) {
      ResponseStarted pigeonResult = new ResponseStarted();
      Object headers = map.get("headers");
      pigeonResult.setHeaders((Map<String, List<String>>)headers);
      Object statusCode = map.get("statusCode");
      pigeonResult.setStatusCode((statusCode == null) ? null : ((statusCode instanceof Integer) ? (Integer)statusCode : (Long)statusCode));
      Object statusText = map.get("statusText");
      pigeonResult.setStatusText((String)statusText);
      Object isRedirect = map.get("isRedirect");
      pigeonResult.setIsRedirect((Boolean)isRedirect);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ReadCompleted {
    private @NonNull byte[] data;
    public @NonNull byte[] getData() { return data; }
    public void setData(@NonNull byte[] setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"data\" is null.");
      }
      this.data = setterArg;
    }

    /**Constructor is private to enforce null safety; use Builder. */
    private ReadCompleted() {}
    public static final class Builder {
      private @Nullable byte[] data;
      public @NonNull Builder setData(@NonNull byte[] setterArg) {
        this.data = setterArg;
        return this;
      }
      public @NonNull ReadCompleted build() {
        ReadCompleted pigeonReturn = new ReadCompleted();
        pigeonReturn.setData(data);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("data", data);
      return toMapResult;
    }
    static @NonNull ReadCompleted fromMap(@NonNull Map<String, Object> map) {
      ReadCompleted pigeonResult = new ReadCompleted();
      Object data = map.get("data");
      pigeonResult.setData((byte[])data);
      return pigeonResult;
    }
  }

  /**
   * Encapsulates a message sent from Cronet to the Dart client.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static class EventMessage {
    private @NonNull EventMessageType type;
    public @NonNull EventMessageType getType() { return type; }
    public void setType(@NonNull EventMessageType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    private @Nullable ResponseStarted responseStarted;
    public @Nullable ResponseStarted getResponseStarted() { return responseStarted; }
    public void setResponseStarted(@Nullable ResponseStarted setterArg) {
      this.responseStarted = setterArg;
    }

    private @Nullable ReadCompleted readCompleted;
    public @Nullable ReadCompleted getReadCompleted() { return readCompleted; }
    public void setReadCompleted(@Nullable ReadCompleted setterArg) {
      this.readCompleted = setterArg;
    }

    /**Constructor is private to enforce null safety; use Builder. */
    private EventMessage() {}
    public static final class Builder {
      private @Nullable EventMessageType type;
      public @NonNull Builder setType(@NonNull EventMessageType setterArg) {
        this.type = setterArg;
        return this;
      }
      private @Nullable ResponseStarted responseStarted;
      public @NonNull Builder setResponseStarted(@Nullable ResponseStarted setterArg) {
        this.responseStarted = setterArg;
        return this;
      }
      private @Nullable ReadCompleted readCompleted;
      public @NonNull Builder setReadCompleted(@Nullable ReadCompleted setterArg) {
        this.readCompleted = setterArg;
        return this;
      }
      public @NonNull EventMessage build() {
        EventMessage pigeonReturn = new EventMessage();
        pigeonReturn.setType(type);
        pigeonReturn.setResponseStarted(responseStarted);
        pigeonReturn.setReadCompleted(readCompleted);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("type", type == null ? null : type.index);
      toMapResult.put("responseStarted", (responseStarted == null) ? null : responseStarted.toMap());
      toMapResult.put("readCompleted", (readCompleted == null) ? null : readCompleted.toMap());
      return toMapResult;
    }
    static @NonNull EventMessage fromMap(@NonNull Map<String, Object> map) {
      EventMessage pigeonResult = new EventMessage();
      Object type = map.get("type");
      pigeonResult.setType(type == null ? null : EventMessageType.values()[(int)type]);
      Object responseStarted = map.get("responseStarted");
      pigeonResult.setResponseStarted((responseStarted == null) ? null : ResponseStarted.fromMap((Map)responseStarted));
      Object readCompleted = map.get("readCompleted");
      pigeonResult.setReadCompleted((readCompleted == null) ? null : ReadCompleted.fromMap((Map)readCompleted));
      return pigeonResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class NativeHttpClientApiCodec extends StandardMessageCodec {
    public static final NativeHttpClientApiCodec INSTANCE = new NativeHttpClientApiCodec();
    private NativeHttpClientApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return EventMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)129:         
          return ReadCompleted.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)130:         
          return ResponseStarted.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value)     {
      if (value instanceof EventMessage) {
        stream.write(128);
        writeValue(stream, ((EventMessage) value).toMap());
      } else 
      if (value instanceof ReadCompleted) {
        stream.write(129);
        writeValue(stream, ((ReadCompleted) value).toMap());
      } else 
      if (value instanceof ResponseStarted) {
        stream.write(130);
        writeValue(stream, ((ResponseStarted) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface NativeHttpClientApi {
    void askCertificateAlias(Result<String> result);
    void initializeClient(@Nullable String alias, Result<Void> result);
    @NonNull String sendRequest(@NonNull String url, @NonNull String method, @NonNull byte[] body, @NonNull Map<String, String> headers);
    void closeClient();
    void dummy(@NonNull EventMessage message);

    /** The codec used by NativeHttpClientApi. */
    static MessageCodec<Object> getCodec() {
      return       NativeHttpClientApiCodec.INSTANCE;    }
    /**Sets up an instance of `NativeHttpClientApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, NativeHttpClientApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.NativeHttpClientApi.askCertificateAlias", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              Result<String> resultCallback = new Result<String>() {
                public void success(String result) {
                  wrapped.put("result", result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.askCertificateAlias(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.NativeHttpClientApi.initializeClient", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              String aliasArg = (String)args.get(0);
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.put("result", null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  wrapped.put("error", wrapError(error));
                  reply.reply(wrapped);
                }
              };

              api.initializeClient(aliasArg, resultCallback);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
              reply.reply(wrapped);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.NativeHttpClientApi.sendRequest", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              String urlArg = (String)args.get(0);
              if (urlArg == null) {
                throw new NullPointerException("urlArg unexpectedly null.");
              }
              String methodArg = (String)args.get(1);
              if (methodArg == null) {
                throw new NullPointerException("methodArg unexpectedly null.");
              }
              byte[] bodyArg = (byte[])args.get(2);
              if (bodyArg == null) {
                throw new NullPointerException("bodyArg unexpectedly null.");
              }
              Map<String, String> headersArg = (Map<String, String>)args.get(3);
              if (headersArg == null) {
                throw new NullPointerException("headersArg unexpectedly null.");
              }
              String output = api.sendRequest(urlArg, methodArg, bodyArg, headersArg);
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.NativeHttpClientApi.closeClient", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              api.closeClient();
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.NativeHttpClientApi.dummy", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              EventMessage messageArg = (EventMessage)args.get(0);
              if (messageArg == null) {
                throw new NullPointerException("messageArg unexpectedly null.");
              }
              api.dummy(messageArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  @NonNull private static Map<String, Object> wrapError(@NonNull Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
